services:
  bff:
    container_name: bff
    image: eai/bff:latest
    ports:
      - "8081:8080"
    environment:
      - API_URL=https://api-2445584177002.staging.gw.apicast.io/virements
      - WEBSOCKET_URL=wss://eai-api.serveo.net/virements
      - SPRING_PROFILES_ACTIVE=prod
      - RHSSO_SERVER_JWK_SET_URI=http://outer_keycloak.serveo.net/realms/EAI_VIREMENTS_BFF/protocol/openid-connect/certs
      - RHSSO_SERVER_JWS_ALGORITHMS=RS256
      - RHSSO_CLIENT_TOKEN_URI=https://eai-rhsso.serveo.net/auth/realms/eai-poc/protocol/openid-connect/token
      - RHSSO_CLIENT_ID=64063030
      - RHSSO_CLIENT_SECRET=7eJHp3dSxKDUFRmQEFEK5SjFbGjyYrTo
    networks:
      - bff_network
  rhsso_database:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_USER=eai
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rhsso
    expose:
      - 5432
    volumes:
      - rhsso_db:/var/lib/postgresql/data
    networks: rhsso_network
  rhsso:
    image: emadou/rhsso:7.6
    ports:
      - 8080:8080
      - 9990:9990
    networks:
      - bff_network
      - rhsso_network
volumes:
  rhsso_db:
    driver: local
networks:
  bff_network:
    driver: bridge
  rhsso_network:
    driver: bridge
