services:
  outer_keycloak:
    container_name: outer_keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "8890:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - outer_keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - openldap_network
    depends_on:
      - openldap
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/data/certificates:/container/service/slapd/assets/certs
      - ./ldap/data/slapd/database:/var/lib/ldap
      - ./ldap/data/slapd/config:/etc/ldap/slapd.d
    env_file:
      - ./ldap.env
    networks:
      - openldap_network
  #phpldapadmin:
  #  image: osixia/phpldapadmin:latest
  #  container_name: phpldapadmin
  #  hostname: phpldapadmin
  #  ports:
  #   - "80:80"
  # environment:
  #   - PHPLDAPADMIN_LDAP_HOSTS=openldap
  #   - PHPLDAPADMIN_HTTPS=false
  # depends_on:
  #   - openldap
  # networks:
  #   - openldap_network

volumes:
  outer_keycloak_data:

networks:
  openldap_network:
    driver: bridge