services:
  api:
    container_name: api
    image: ghcr.io/iou4/virement-api:main
    networks:
      - api_network
    ports:
      - "8082:8080"
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./api/.env
  database:
    container_name: virement_database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network
    env_file:
      - ./api/.env

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
