spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${POSTGRES_DB:virement}
    username: ${POSTGRES_USER:eai}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
