server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${POSTGRES_DB:virement}
    username: ${POSTGRES_USER:eai}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
