spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:virement}
    username: ${DB_USER:eai}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
