api:
  url: ${API_URL}
server:
  port: 8080
logging:
  level:
    root: warn
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${RHSSO_TOKEN_URI}
        registration:
          keycloak:
            client-id: ${RHSSO_CLIENT_ID}
            client-secret: ${RHSSO_CLIENT_SECRET}
            authorization-grant-type: client_credentials