api:
  rest:
    base: ${API_REST_DOMAIN_URL}
    endpoints:
      balance: ${API_BALANCE_ENDPOINT}
      virement: ${API_VIREMENT_ENDPOINT}
      loyalty: ${API_LOYALTY_ENDPOINT}
  websocket:
    base: ${API_WEBSOCKET_DOMAIN_URL}
    topics:
      virement: ${API_VIREMENT_WEBSOCKET_TOPIC}
server:
  port: 8080
logging:
  level:
    root: debug
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${RHSSO_SERVER_JWK_SET_URI}
          jws-algorithms: ${RHSSO_SERVER_JWS_ALGORITHMS:RS256}
      client:
        provider:
          keycloak:
            token-uri: ${RHSSO_CLIENT_TOKEN_URI}
        registration:
          keycloak:
            client-id: ${RHSSO_CLIENT_ID}
            client-secret: ${RHSSO_CLIENT_SECRET}
            authorization-grant-type: client_credentials
