api:
  rest:
    base: ${API_BASE_URL}
    domains:
      balance: ${API_BALANCE_DOMAIN_URL:/balance}
      virement: ${API_VIREMENT_DOMAIN_URL:/virement}
      loyalty: ${API_LOYALTY_DOMAIN_URL:/loyalty}
  websocket:
    base: ${API_WEBSOCKET_BASE_URL}
    topics:
      virement: ${API_VIREMENT_WEBSOCKET_TOPIC_URL:/virement}
server:
  port: 8080
logging:
  level:
    root: warn
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${RHSSO_SERVER_JWK_SET_URI}
          jws-algorithms: ${RHSSO_SERVER_JWS_ALGORITHMS:RS256}
      client:
        provider:
          keycloak:
            token-uri: ${RHSSO_CLIENT_TOKEN_URI}
        registration:
          keycloak:
            client-id: ${RHSSO_CLIENT_ID}
            client-secret: ${RHSSO_CLIENT_SECRET}
            authorization-grant-type: client_credentials
