api:
  rest:
    base: https://api-2445584177002.staging.gw.apicast.io
    endpoints:
      virement: /virement
      balance: /balance
      loyalty: /loyalty
  websocket:
    base: wss://api-2445584177002.staging.gw.apicast.io
    topics:
      virement: /virement
server:
  port: 8082
logging:
  level:
    root: debug
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8890/realms/EAI_VIREMENTS_BFF/protocol/openid-connect/certs
          jws-algorithms: RS256
      client:
        provider:
          keycloak:
            token-uri: https://eai-rhsso.serveo.net/auth/realms/eai-poc/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: 64063030
            client-secret: 7eJHp3dSxKDUFRmQEFEK5SjFbGjyYrTo
            authorization-grant-type: client_credentials
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
