api:
  url: https://api-2445584177002.staging.gw.apicast.io
server:
  port: 8081
  netty:
    connection-timeout: -1
springdoc:
  api-docs:
    version: openapi_3_0
    path: /docs/openapi
logging:
  level:
    root: debug
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://eai-rhsso.serveo.net/auth/realms/eai-poc/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: 64063030
            client-secret: YszfZ1bW9i2yf3HExsfKIbeJHhwNSQyH
            authorization-grant-type: client_credentials
