api:
  rest:
    balance: ${API_BALANCE_DOMAIN_URL}
    virement: ${API_VIREMENT_DOMAIN_URL}
    loyalty: ${API_LOYALTY_DOMAIN_URL}
  websocket:
    virement: ${API_VIREMENT_WEBSOCKET_TOPIC_URL}
server:
  port: 8080
logging:
  level:
    root: warn
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${RHSSO_SERVER_JWK_SET_URI}
          jws-algorithms: ${RHSSO_SERVER_JWS_ALGORITHMS:RS256}
      client:
        provider:
          keycloak:
            token-uri: ${RHSSO_CLIENT_TOKEN_URI}
        registration:
          keycloak:
            client-id: ${RHSSO_CLIENT_ID}
            client-secret: ${RHSSO_CLIENT_SECRET}
            authorization-grant-type: client_credentials
