api:
  url: https://api-2445584177002.staging.gw.apicast.io
  websocket: wss://socketsbay.com/wss/v2/1/demo/
server:
  port: 8081
logging:
  level:
    root: debug
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://eai-rhsso.serveo.net/auth/realms/eai-poc/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: 64063030
            client-secret: YszfZ1bW9i2yf3HExsfKIbeJHhwNSQyH
            authorization-grant-type: client_credentials
